(define (domain railway)
    (:requirements :strips :typing :numeric-fluents :durative-actions)
    (:types track-point train gauge-type engine station)
    (:predicates
        (train-at ?tr - train ?pt - track-point)
        (engine-at ?en - engine ?pt - track-point)
        (connected ?from - track-point ?to - track-point)
        (not-connected ?from - track-point ?to - track-point)
        (track-accessible ?from - track-point ?to - track-point)
        (free ?pt - track-point)
        (junction-point ?pt - track-point)
        (turnout-alternatives ?jp - track-point ?alt1 - track-point ?alt2 - track-point)
        (train-gauge ?tr - train ?gt - gauge-type)
        (engine-gauge ?en - engine ?gt - gauge-type)
        (track-gauge ?from - track-point ?to - track-point ?gt - gauge-type)
        (track-blocked ?from - track-point ?to - track-point)
        (track-clear ?from - track-point ?to - track-point)
        (train-blocked ?tr - train ?pt - track-point)
        (train-not-blocked ?tr - train ?pt - track-point)
        (engine-damaged ?tr - train ?pt - track-point)
        (engine-not-damaged ?tr - train ?pt - track-point)
        (boarding-point ?tr - train ?pt - track-point)
        (passengers-boarded ?tr - train ?pt - track-point)
        (engine-free ?en - engine)
        (engine-attached ?en - engine ?tr - train)
        (upward ?p1 - track-point ?p2 - track-point)
        (downward ?p1 - track-point ?p2 - track-point)
        (train-going-up ?tr - train)
        (train-going-down ?tr - train)
        (engine-going-up ?en - engine)
        (engine-going-down ?en - engine)
        (platform-at ?pt - track-point ?stn - station))
    (:functions
        (distance ?from - track-point ?to - track-point)
        (train-speed ?tr - train)
        (engine-speed ?en - engine)
        (track-clear-time ?from - track-point ?to - track-point)
        (train-blockage-time ?tr - train ?pt - track-point)
        (engine-attach-time ?en - engine)
        (slowdown ?from - track-point ?to - track-point)
        (turnout-time)
        (boarding-time ?tr - train ?stn - station))

    (:durative-action drive-train
        :parameters (?tr - train ?from - track-point ?to - track-point ?gt - gauge-type)
        :duration (= ?duration (/ (distance ?from ?to) (* (train-speed ?tr) (- 1 (slowdown ?from ?to)))))
        :condition (and 
            (at start (train-at ?tr ?from))
            (at start (train-gauge ?tr ?gt))
            (at start (track-gauge ?from ?to ?gt))
            (at start (train-not-blocked ?tr ?from))
            (at start (track-clear ?from ?to))
            (at start (engine-not-damaged ?tr ?from))
            (at start (track-accessible ?from ?to))
            (over all (connected ?from ?to))
            (over all (free ?to))
            (at end (free ?to)))
        :effect (and 
            (at start (not (train-at ?tr ?from)))
            (at start (free ?from))
            (at start (not (track-accessible ?from ?to)))
            (at start (not (track-accessible ?to ?from)))
            (at end (train-at ?tr ?to))
            (at end (not (free ?to)))
            (at end (track-accessible ?from ?to))
            (at end (track-accessible ?to ?from))))

    (:durative-action drive-engine
        :parameters (?en - engine ?from - track-point ?to - track-point ?gt - gauge-type)
        :duration (= ?duration (/ (distance ?from ?to) (* (engine-speed ?en) (- 1 (slowdown ?from ?to)))))
        :condition (and 
            (at start (engine-at ?en ?from))
            (at start (engine-free ?en))
            (at start (engine-gauge ?en ?gt))
            (at start (track-gauge ?from ?to ?gt))
            (at start (track-clear ?from ?to))
            (at start (track-accessible ?from ?to))
            (over all (connected ?from ?to))
            (over all (free ?to))
            (at end (free ?to)))
        :effect (and 
            (at start (not (engine-at ?en ?from)))
            (at start (free ?from))
            (at start (not (track-accessible ?from ?to)))
            (at start (not (track-accessible ?to ?from)))
            (at end (engine-at ?en ?to))
            (at end (not (free ?to)))
            (at end (track-accessible ?from ?to))
            (at end (track-accessible ?to ?from))))

    (:durative-action drive-engine-to-damaged-up-train
        :parameters (?en - engine ?tr - train ?from - track-point ?to - track-point ?gt - gauge-type)
        :duration (= ?duration (/ (distance ?from ?to) (* (engine-speed ?en) (- 1 (slowdown ?from ?to)))))
        :condition (and 
            (at start (engine-at ?en ?from))
            (at start (engine-free ?en))
            (at start (engine-gauge ?en ?gt))
            (at start (track-gauge ?from ?to ?gt))
            (at start (train-gauge ?tr ?gt))
            (at start (upward ?from ?to))
            (at start (train-going-up ?tr))
            (at start (train-at ?tr ?to))
            (at start (engine-damaged ?tr ?to))
            (at start (track-clear ?from ?to))
            (at start (track-accessible ?from ?to))
            (at start (engine-going-down ?en))
            (over all (connected ?from ?to))
            (over all (train-at ?tr ?to)))
        :effect (and 
            (at start (not (engine-at ?en ?from)))
            (at start (free ?from))
            (at start (not (track-accessible ?from ?to)))
            (at start (not (track-accessible ?to ?from)))
            (at end (engine-at ?en ?to))
            (at end (track-accessible ?from ?to))
            (at end (track-accessible ?to ?from))
            (at end (engine-going-up ?en))
            (at end (not (engine-going-down ?en)))))

    (:durative-action drive-engine-to-damaged-down-train
        :parameters (?en - engine ?tr - train ?from - track-point ?to - track-point ?gt - gauge-type)
        :duration (= ?duration (/ (distance ?from ?to) (* (engine-speed ?en) (- 1 (slowdown ?from ?to)))))
        :condition (and 
            (at start (engine-at ?en ?from))
            (at start (engine-free ?en))
            (at start (engine-gauge ?en ?gt))
            (at start (track-gauge ?from ?to ?gt))
            (at start (train-gauge ?tr ?gt))
            (at start (downward ?from ?to))
            (at start (train-going-down ?tr))
            (at start (train-at ?tr ?to))
            (at start (engine-damaged ?tr ?to))
            (at start (track-clear ?from ?to))
            (at start (track-accessible ?from ?to))
            (at start (engine-going-up ?en))
            (over all (connected ?from ?to))
            (over all (train-at ?tr ?to)))
        :effect (and 
            (at start (not (engine-at ?en ?from)))
            (at start (free ?from))
            (at start (not (track-accessible ?from ?to)))
            (at start (not (track-accessible ?to ?from)))
            (at end (engine-at ?en ?to))
            (at end (track-accessible ?from ?to))
            (at end (track-accessible ?to ?from))
            (at end (engine-going-down ?en))
            (at end (not (engine-going-up ?en)))))

    (:durative-action attach-engine
        :parameters (?en - engine ?tr - train ?pt - track-point)
        :duration (= ?duration (engine-attach-time ?en))
        :condition (and 
            (at start (engine-at ?en ?pt))
            (at start (train-at ?tr ?pt))
            (at start (engine-free ?en))
            (at start (engine-damaged ?tr ?pt))
            (over all (engine-at ?en ?pt))
            (over all (train-at ?tr ?pt)))
        :effect (and 
            (at start (not (engine-free ?en)))
            (at end (engine-attached ?en ?tr))))

    (:durative-action drive-assisted-train
        :parameters (?en - engine ?tr - train ?from - track-point ?to - track-point ?gt - gauge-type)
        :duration (= ?duration (/ (distance ?from ?to) (* (engine-speed ?en) (- 1 (slowdown ?from ?to)))))
        :condition (and 
            (at start (engine-attached ?en ?tr))
            (at start (train-at ?tr ?from))
            (at start (engine-at ?en ?from))
            (at start (engine-gauge ?en ?gt))
            (at start (track-gauge ?from ?to ?gt))
            (at start (track-clear ?from ?to))
            (at start (train-not-blocked ?tr ?from))
            (at start (track-accessible ?from ?to))
            (over all (free ?to))
            (over all (connected ?from ?to))
            (at end (free ?to)))
        :effect (and 
            (at start (not (train-at ?tr ?from)))
            (at start (not (engine-at ?en ?from)))
            (at start (free ?from))
            (at start (not (track-accessible ?from ?to)))
            (at start (not (track-accessible ?to ?from)))
            (at start (not (engine-damaged ?tr ?from)))
            (at start (engine-not-damaged ?tr ?from))
            (at end (train-at ?tr ?to))
            (at end (engine-at ?en ?to))
            (at end (not (free ?to)))
            (at end (track-accessible ?from ?to))
            (at end (track-accessible ?to ?from))
            (at end (engine-damaged ?tr ?to))
            (at end (not (engine-not-damaged ?tr ?to)))))

    (:durative-action resolve-train-blockage
        :parameters (?tr - train ?pt - track-point)
        :duration (= ?duration (train-blockage-time ?tr ?pt))
        :condition (and 
            (at start (train-blocked ?tr ?pt))
            (at start (train-at ?tr ?pt))
            (over all (train-at ?tr ?pt)))
        :effect (and 
            (at end (not (train-blocked ?tr ?pt)))
            (at end (train-not-blocked ?tr ?pt))))

    (:durative-action clear-blocked-track
        :parameters (?from - track-point ?to - track-point)
        :duration (= ?duration (track-clear-time ?from ?to))
        :condition (at start (track-blocked ?from ?to))
        :effect (and 
            (at end (not (track-blocked ?from ?to)))
            (at end (not (track-blocked ?to ?from)))
            (at end (track-clear ?from ?to))
            (at end (track-clear ?to ?from))))

    (:durative-action board-passengers
        :parameters (?tr - train ?stn - station ?pt - track-point)
        :duration (= ?duration (boarding-time ?tr ?stn))
        :condition (and 
            (at start (train-at ?tr ?pt))
            (at start (boarding-point ?tr ?pt))
            (at start (platform-at ?pt ?stn))
            (over all (train-at ?tr ?pt)))
        :effect (at end (passengers-boarded ?tr ?pt)))

    (:durative-action turnout
        :parameters (?tp - track-point ?alt1 - track-point ?alt2 - track-point)
        :duration (= ?duration (turnout-time))
        :condition (and 
            (at start (junction-point ?tp))
            (at start (turnout-alternatives ?tp ?alt1 ?alt2))
            (at start (connected ?tp ?alt1))
            (at start (not-connected ?tp ?alt2)))
        :effect (and 
            (at start (not (connected ?tp ?alt1)))
            (at start (not (connected ?alt1 ?tp)))
            (at start (not-connected ?tp ?alt1))
            (at start (not-connected ?alt1 ?tp))
            (at end (connected ?tp ?alt2))
            (at end (connected ?alt2 ?tp))
            (at end (not (not-connected ?tp ?alt2)))
            (at end (not (not-connected ?alt2 ?tp)))))
)
